name: XDUPile Script

on:
  schedule:
    - cron: 0 4,22 * * *
  push:
    - branch: [ "main" ]

jobs:

  Build_and_Run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -o ./exe

    - name: Run
      run: ./exe
      env: 
        EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        POST_BODY: ${{ secrets.POST_BODY }}
        XDU_ACCOUNT: ${{ secrets.XDU_ACCOUNT }}
        XDU_PASSWORD: ${{ secrets.XDU_PASSWORD }}
        
