name: XDUPile Script

on:
  schedule:
    - cron: 30,59 4 * * *
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  Build_and_Run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -o ./exe

    - name: Run
      run: ./exe
